### ISSUE TITLE
quoteParamIfNeeded

### ISSUE THREAD

**Issue by oneEyedSunday** [Tiemma/sonic-dr#3]
You really should implement `quoteParamIfNeeded` stuff like `Group`, `Key` are fairly common table names.
Its also used in ` cleanRowData`.

I guess one could find a list of keywords in Postgres and MySql (by versions) and just only quote them, or just quote everything like ORMs do when handling migrations and co.

I know you'd get to do this (or expect PRs), so I'm opening this so (future) me (or someone else) has some info.

**Comment by tiemma** [comment]
Are you asking I quote all params?

That would cause errors as some fields don't need to be quoted in certain databases e.g MySQL

Postgres is case sensitive so quoting means using the keyword as in its case, without it, it will be set in lowercase

A better description of this issue might help in resolving it. or you can propose an example like I've done above
